.TH vbsim 1 "January, 2011 (v1.8.5)" "VoxBo" "The VoxBo Manual"
.SH NAME
vbsim - create random data for neuroimaging
.SH SYNOPSIS
.B vbsim
<flag> ...
.SH DESCRIPTION
.B vbsim
is part of the VoxBo suite of tools for brain image analysis.
.P
.B vbsim
allows you to create 1D vectors, 3D volumes, or 4D volume series
filled with Gaussian random data.  The supported output file formats
are described in voxbo-fileformats(7).
.P
For detailed information on usage and options, run the program with no
arguments.
.SH AVAILABILITY
Pre-built VoxBo binaries are available for Linux, OSX, and Cygwin, and
via the NeuroDebian project (neuro.debian.net) for Debian derivatives.
.SH CAVEATS
VoxBo is provided with no warranty whatsoever.
.SH AUTHOR
For an historical roster of the VoxBo development team, visit
www.voxbo.org.
.SH SEE ALSO
For detailed help on any VoxBo command-line program, run it with no
arguments.  For graphical programs, use the -h flag.  For more help
with VoxBo, for information about the mailing list, or to report bugs,
visit the web site at www.voxbo.org.
.P
For information about file format support in VoxBo, see
.BR voxbo-fileformats (7).
For general information about VoxBo, see
.BR voxbo (7).
