.TH vbview2 1 "January, 2011 (v1.8.5)" "VoxBo" "The VoxBo Manual"
.SH NAME
vbview2 - image viewer for 3D and 4D volumes
.SH SYNOPSIS
.B vbview2
<flag> ...
.SH DESCRIPTION
.B vbview2
is part of the VoxBo suite of tools for brain image analysis.
.P
.B vbview2
is an image viewer for to 3D and 4D images.  It displays slices, not
projections or surface renderings.  It allows an arbitrary number of
layers and graphs time series data.
.SH OPTIONS
To get a complete list of available flags, run the program with the -h
argument.
.SH AVAILABILITY
Pre-built VoxBo binaries are available for Linux, OSX, and Cygwin, and
via the NeuroDebian project (neuro.debian.net) for Debian derivatives.
.SH CAVEATS
VoxBo is provided with no warranty whatsoever.
.SH AUTHOR
For an historical roster of the VoxBo development team, visit
www.voxbo.org.
.SH SEE ALSO
For detailed help on any VoxBo command-line program, run it with no
arguments.  For graphical programs, use the -h flag.  For more help
with VoxBo, for information about the mailing list, or to report bugs,
visit the web site at www.voxbo.org.
.P
For information about file format support in VoxBo, see
.BR voxbo-fileformats (7).
For general information about VoxBo, see
.BR voxbo (7).
